### ISSUE TITLE
Support pseudo-transparent backgrounds

### ISSUE THREAD

**Issue by ryuslash** [retroj/mowedline#13]
It'd be very nice if mowedline supported pseudo-transparent backgrounds. A very quick search resulted in [this](http://fixunix.com/xwindows/91686-xlib-pseudo-transparency-example-needs-polish-print.html) (hopefully working) example. I'm going to try to look into it soon, but if I don't I hope this link is helpful.

**Comment by retroj** [comment]
Implemented.  To use it: (window-background 'inherit)
