### ISSUE TITLE
background 'inherit - repaint problem with compton

### ISSUE THREAD

**Issue by retroj** [retroj/mowedline#15]
Mowedline seems not to play nice with compositors, like compton, when the window background is 'inherit.  Compositors create a window between the root window and the clients, so when the client uses ParentRelative for its background pixmap, as mowedline does in 'inherit mode, the previous contents of the mowedline window are used for its own background, instead of the true root window background pixmap.  Effectively, this looks like xcleararea is not working, but it is working - it's just clearing to the last drawn window contents, due to the way that compositors work.

**Comment by retroj** [comment]
I did a test.  I wanted to see whether using XClearArea piece-meal over the window instead of repainting the whole window each time with XClearWindow was the problem.  When I changed mowedline to use XClearWindow instead of XClearArea, the problem persisted, so that's not it.

**Comment by retroj** [comment]
Some research tells me the right way to have transparency with a compositor is actually to create the window with a 32 bit visual and set the background to a pixmap with alpha 0.  Mowedline currently uses XCreateSimpleWindow to make its windows, so we will need to switch to XCreateWindow instead to  get this feature.  For the user interface, I think we can expose this option via (window-background 'transparent).

**Comment by retroj** [comment]
Running into a mysterious problem with XCreateWindow that I first encountered back in commit 6f20d686b89943d6078bc289f89723ebb7aec5b1.

```
  X Error of failed request:  BadMatch (invalid parameter attributes)
    Major opcode of failed request:  1 (X_CreateWindow)
    Serial number of failed request:  10
    Current serial number in output stream:  13
```

Have ruled out dbus.  The error doesn't happen immediately at the call to XCreateWindow but at subsequent calls like setting properties on the window, or other things.  Ryuslash was able to make a small test case that reproduces the error.

**Comment by retroj** [comment]
Progress.  The mysterious error was due to getting a Visual in the wrong way.  In commit c7c9441 we now get a valid visual structure to pass to XCreateWindow.

**Comment by retroj** [comment]
and done..

```
(window-background 'transparent)
```

**Comment by ryuslash** [comment]
Awesome! It works very nicely!
