### ISSUE TITLE
mowedline sometimes quits

### ISSUE THREAD

**Issue by ryuslash** [retroj/mowedline#8]
Sometimes mowedline just seems to quit. I can't reliably reproduce this yes, but it seems to have to do with starting other graphical application, or performing certain actions. This mostly seems to happen when I start mowedline from my `.xinitrc`, however it also sometimes happens when starting mowedline from the command-line. 

No output is produced when this happens.

I will investigate some more and if I find anything I'll expand this issue accordingly.

**Comment by retroj** [comment]
commit d0c20b9

A number of online examples show simple Xlib programs quitting on ClientMessage, however I haven't found any stated reason to do so. ClientMessage events may be any information passed from one client to another, not just a "close" request.  This code is clearly wrong in the general case, so I'm removing it until and if I find some more specific "close" request that must be handled.

**Comment by retroj** [comment]
There is a type of ClientMessage that is a quit request, and mowedline now supports it.  It's a ClientMessage with message_type (atom)WM_PROTOCOL and data_l[0] == (atom)WM_DELETE_WINDOW.  I still have to test the code, but I believe it's correct now. (commit 06cd0380)

**Comment by retroj** [comment]
tested.  it works.  closing issue.  hopefully that is all the mysterious quitting was.

**Comment by retroj** [comment]
by the way, for future reference, what i did to test it was to remove the OverrideRedirect flag from the mowedline window so that the window manager would manage it, then use my window manager's 'close' key on the mowedline window.  It quit as expected when the clientmessage handler was in place, and not when it was not.
